### ISSUE TITLE
Invalid format when saving XML file (partition)

### ISSUE THREAD

**Issue by Narduzzi** [Narduzzi/StartHack2017#2]
Error when saving the partition (pressing **space** in _recording mode_).
Error message : 
![2017-05-19](https://cloud.githubusercontent.com/assets/5306860/26243166/2e167252-3c8b-11e7-8d60-196657116201.png)
![2017-05-19 2](https://cloud.githubusercontent.com/assets/5306860/26243221/661d38e8-3c8b-11e7-9192-98432ebb022d.png)

**Comment by omacha** [comment]
Fixed in 4d9b781ca25eb5e441c9ee8d3168370a173d838a on branch origin/piano (please merge back to master).

**Please be careful: the creation logic is different from the reading logic ! Also, the creation code *only works in the Unity Editor*.**
